### ISSUE TITLE
Missing issuer_id when it clearly isn't.

### ISSUE THREAD

**Issue by losh11** [bitrise-steplib/steps-ios-auto-provision-appstoreconnect#12]
```
Config:
- BuildAPIToken: [REDACTED]
- BuildURL: https://app.bitrise.io/build/463f3a302790beae
- ProjectPath: ios/lndmobile.xcworkspace
- Scheme: lndmobile
- Configuration: 
- Distribution: development
- MinProfileDaysValid: 0
- CertificateURLList: [REDACTED]
- CertificatePassphraseList: *****
- KeychainPath: /Users/vagrant/Library/Keychains/login.keychain
- KeychainPassword: *****
- VerboseLog: false
Creating AppstoreConnectAPI client
Failed get developer portal data: invalid App Store Connect API authentication data: missing issuer_id
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | ios-auto-provision-appstoreconnect@0 (exit code: 1)           | 12.16 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...se-steplib/steps-ios-auto-provision-appstoreconnect/issues |
| Source: ...thub.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect |
+---+---------------------------------------------------------------+----------+
```

<img width="1394" alt="apple" src="https://user-images.githubusercontent.com/2608570/88209483-b08e8d80-cc4a-11ea-98c0-8bf7b2474edd.png">

I even copied the issuer ID using the copy button on the AppStore Connect site.

**Comment by bitce** [comment]
Hi @losh11!

Sorry to hear about the issue. Can you confirm that on the Team tab of this app, this very same account is selected for the step to be using?

**Comment by losh11** [comment]
Hi yes, I can confirm that the team is the same. Though in Xcode we are signing into a team account which has the same team ID.

**Comment by bitce** [comment]
Thanks! Can you please send us a link to this build an enable Support User access in the Settings of the app?

**Comment by losh11** [comment]
Done - https://app.bitrise.io/app/f9a0d0dccb8b0636
not sure if that's the correct link

**Comment by luis-f-lins** [comment]
Any updates on this? I've also had this problem with `missing issuer_id`, even though everything seems correct in my Bitrise profile

**Comment by bitce** [comment]
Hi @losh11  

When I said 

> can you confirm that on the Team tab of this app, this very same account is selected for the step to be using?

I mean that your project on the website has a "team tab" where you have to select this account. Can you confirm that thisi s done?
![Screenshot from 2020-08-04 09-17-12](https://user-images.githubusercontent.com/40164469/89264613-81592280-d633-11ea-8415-c0367bf792de.png)

**Comment by losh11** [comment]
Okay that works. Though I'm still getting another issue:

```Checking if 1 Bitrise test device(s) are registered on Developer Portal
28 devices are registered on Developer Portal
checking if the device (PEEPEEPOOPOOPEEPEEPOO) is registered
registering device
Failed to register device: json: cannot unmarshal object into Go struct field DevicesResponse.data of type []appstoreconnect.Device```

**Comment by bitce** [comment]
Glad to hear about the progress! The error seems related to the step trying to register test devices for your developer portal account. Can you try to reset your device list over there?

**Comment by losh11** [comment]
I've tried resetting the device list. FYI building via xcode etc works, it's specifically just bitrise's autoprovision failing.

**Comment by bitce** [comment]
Right! Sorry I missed this earlier, what's happening is that the step is trying to register test devices for you, and somebody associated with the app had the UDID "PEEPEEPOOPOOPEEPEEPOO" registered, which is of course, incorrect. As I can see you've since removed it and the latest builds passed, but let me know if I'm wrong and you'd need further help with this!
