### ISSUE TITLE
Failed to apply code sign settings

### ISSUE THREAD

**Issue by vapor-pawelw** [bitrise-steplib/steps-ios-auto-provision-appstoreconnect#21]
Hello,

I had just introduced this step instead of the Apple ID one and it seems to be failing on most of my workflows :(

One where I build a debug scheme for Bitrise adhoc deployment, getting this error (I replaced the real app name with "$appname" everywhere in the logs):

```
Failed to apply code sign settings for target ($appname-dev): failed to change code signing in target attributes, error: failed to get traget's (C9C0280F2434BCF4004BA737) attributes, error: key: string("C9C0280F2434BCF4004BA737") not found in: serialized.Object(serialized.Object{"079F11AB1D50B63A00071DD8":map[string]interface {}{"CreatedOnToolsVersion":"7.3.1", "LastSwiftMigration":"0810", "ProvisioningStyle":"Automatic", "SystemCapabilities":map[string]interface {}{"com.apple.AutoFillCredentialProvider":map[string]interface {}{"enabled":"0"}, "com.apple.BackgroundModes":map[string]interface {}{"enabled":"1"}, "com.apple.InAppPurchase":map[string]interface {}{"enabled":"1"}, "com.apple.Keychain":map[string]interface {}{"enabled":"1"}, "com.apple.Push":map[string]interface {}{"enabled":"1"}, "com.apple.SafariKeychain":map[string]interface {}{"enabled":"1"}}}, "5E12D9351DEF1CFE001AA967":map[string]interface {}{"CreatedOnToolsVersion":"8.1", "DevelopmentTeam":"N262PL6K8J", "LastSwiftMigration":"1130", "ProvisioningStyle":"Automatic"}, "C901E33023E0E61C0078642D":map[string]interface {}{"CreatedOnToolsVersion":"11.3", "DevelopmentTeam":"N262PL6K8J", "LastSwiftMigration":"1130", "ProvisioningStyle":"Manual"}, "C901E38223E0EC100078642D":map[string]interface {}{"CreatedOnToolsVersion":"11.3", "DevelopmentTeam":"N262PL6K8J", "ProvisioningStyle":"Manual"}, "C997BB5E24ADCDEC00957DBC":map[string]interface {}{"CreatedOnToolsVersion":"11.5"}, "C9A116F02506349600162BC3":map[string]interface {}{"CreatedOnToolsVersion":"12.0"}, "C9C04D0623E32049009D0CAB":map[string]interface {}{"CreatedOnToolsVersion":"11.3"}, "C9DBC11325221AD4001CD914":map[string]interface {}{"CreatedOnToolsVersion":"12.0"}, "F901069E2375A9B40075F52F":map[string]interface {}{"CreatedOnToolsVersion":"11.1", "DevelopmentTeam":"N262PL6K8J", "ProvisioningStyle":"Automatic"}, "F9C1DB252201D10500219058":map[string]interface {}{"CreatedOnToolsVersion":"10.1", "DevelopmentTeam":"N262PL6K8J", "LastSwiftMigration":"1010", "ProvisioningStyle":"Automatic", "SystemCapabilities":map[string]interface {}{"com.apple.BackgroundModes":map[string]interface {}{"enabled":"1"}, "com.apple.InAppPurchase":map[string]interface {}{"enabled":"1"}, "com.apple.Push":map[string]interface {}{"enabled":"1"}}}})
```

Another problem I've got is that in my test workflow, xcode analyze step (latest version) is failing, with these errors:

```
Last lines of the Xcode's build log:
2020-10-27 15:50:34.176 xcodebuild[3196:20856] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 113. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2020-10-27 15:50:34.203 xcodebuild[3196:20856] Error Domain=NSCocoaErrorDomain Code=3840 "No string key for value in object around character 1." UserInfo={NSDebugDescription=No string key for value in object around character 1.}
2020-10-27 15:50:34.206 xcodebuild[3196:20856] [MT] IDEFileReferenceDebug: [Load] <IDEFileReference, 0x7fec7bb57310: name:$appname path:group:$appname.xcodeproj> Failed to load container at path: /Users/vagrant/git/$appname.xcodeproj, Error: Error Domain=Xcode3ProjectErrorDomain Code=2 "The project ‘$appname’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.
Path: /Users/vagrant/git/$appname.xcodeproj" UserInfo={NSLocalizedDescription=The project ‘$appname’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.
Path: /Users/vagrant/git/$appname.xcodeproj}
```

**Comment by vapor-pawelw** [comment]
After trying to manually add targets info to TargetAttributes to the pbxproj, I'm now getting this error
```
Failed to open project: /Users/vagrant/git/$appname.xcworkspace: could not get scheme ($appname-dev) from path (/Users/vagrant/git/$appname.xcworkspace): failed to generate json from Pbxproj - error: plist: error parsing text property list: missing ; in dictionary at line 112 character 86865
```

**Comment by non-binary** [comment]
Hi @vapor-pawelw,

Thank you for reaching out.

I have escalated this to our L3 team to investigate.

**Comment by vapor-pawelw** [comment]
@non-binary any updates on this and any estimated time when the fix could be expected?

**Comment by mjones-droid** [comment]
Hey @vapor-pawelw!

This is a known bug with certain projects. We have a bug report filed with the dev's. In the mean time I suggest switching to the [older Apple ID step](https://www.bitrise.io/integrations/steps/ios-auto-provision).

**Comment by mjones-droid** [comment]
In regards to this specific error:

`failed to generate json from Pbxproj - error: plist: error parsing text property list: missing ; in dictionary at line 112 character 86865`

We've discovered that the organization name isn't properly escaped for some customers. It's possible changing your org name will help with that one.

**Comment by vapor-pawelw** [comment]
@mjones-droid Thank you for the information - yes, we already went back for Apple ID step so we could keep our workflows working.

As for the plist error - changing org name is not an option for us at the moment. I don't know why is that, our org name contains just ascii and dots and is a standard reverse-domain format.  It would be great if you would be able to address this issue as well in some of the upcoming updates :)

**Comment by mjones-droid** [comment]
Howdy @vapor-pawelw! 

As we've continued to investigate this issue, there are other fields that aren't being escaped properly as well. It might be worth taking a look through the Xcode project fields for any characters that commonly need escaped. 

In the mean time, our dev's are aware of the issue and a bug fix is planned for an upcoming sprint.

**Comment by vapor-pawelw** [comment]
Great! :) Hope it's coming soon. Thank you!

**Comment by godrei** [comment]
Hi @vapor-pawelw , we introduced fixes for the step around project parsing and codesign setting. Could you please try the latest version of the step ([0.1.7](https://github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/releases/tag/0.1.7))?

**Comment by godrei** [comment]
Closing as we did not receive a reply - @vapor-pawelw please let us know if we can help with anything by opening a new issue!
