### ISSUE TITLE
Plugin fails to provision for stand-alone watchOS apps

### ISSUE THREAD

**Issue by bangfalse** [bitrise-steplib/steps-ios-auto-provision-appstoreconnect#22]
After printing the bundle IDs of my watchkitapp and watchkitapp.watchkitextension, the step prints:
`Failed to read project platform: not supported platform. Platform (PLATFORM_DISPLAY_NAME) = watchOS, supported: iOS, tvOS`
and fails with exit code 1.

**Comment by chaitanyatanna-bitrise** [comment]
Hello @bangfalse 
Could you please provide the build URL and enable Support Access?
I am going to discuss this with my team as well.

Thanks
Chaitanya

**Comment by bangfalse** [comment]
Here's a failing build: https://app.bitrise.io/build/d247a89ec91b6d95
Here's the successful build after manually uploading updated profiles and switching back to `certificate-and-profile-installer@1`: https://app.bitrise.io/build/33a24cdb8e83dd0f

Support access is enabled.

**Comment by chaitanyatanna-bitrise** [comment]
Hello @bangfalse 
I am glad that the issue is resolved. 
When you are using the certificate and profile installer step, you need to upload the profiles and certificates manually to the bitrise Codesigning tab.
Is there anything else I can help you with?

Thanks
Chaitanya

**Comment by bangfalse** [comment]
I would not consider this a resolution, since it requires me to upload a new set of provisioning profiles every week. If this step were working correctly, there would not be manual weekly maintenance needed to my workflow.

**Comment by chaitanyatanna-bitrise** [comment]
Hi @bangfalse 
Is there any reason you need to upload the provisioning profiles every week?
Are you getting any error after every week regarding the profiles?
If so, can you provide more details on it, please?

Thanks
Chaitanya

**Comment by bangfalse** [comment]
The two first sets of `app-store` provisioning profiles issued by Apple and gathered by `codesigndoc` had only been valid for a week each when I first started testing this app. I use Apple's automatically manage singing setting, so this is somewhat opaque to me.

Now it appears that Apple has granted me provisioning profiles that are good for a year, so this is less of a concern.

I would still consider this an issue with this step, but since there's a decent workaround, it's more of a "feature enhancement request" than a "blocking issue".

**Comment by cathyharmon** [comment]
Hello,

We can certainly take a deeper look into why the iOS Auto Provision step was failing.  Unfortunately, the support access has expired. 

You may also wish to consider opening a support ticket as there may be information we need that you might not want to publicly share.

Cathy
