### ISSUE TITLE
Fails with App Clip target

### ISSUE THREAD

**Issue by mbuchetics** [bitrise-steplib/steps-ios-auto-provision-appstoreconnect#23]
Since adding an app clip target to my project, this step fails with the following error:

```
Searching for app ID for bundle ID: at.tinkado.Flipbook.Clip
  app ID found: XC at tinkado Flipbook Clip
  app ID capabilities are not in sync with the project capabilities, synchronizing...
This will enable the "App Groups" capability but details will have to be configured manually using the Apple Developer Portal
failed to update bundle ID capabilities: step does not support creating an application identifier using the "Parent Bundle ID" capability, please add your Application Identifier manually using the Apple Developer Portal
```

When checking the settings in the developer portal, everything looks fine. Xcode also archives & exports without an issue.

The build log is here: https://app.bitrise.io/build/2a2961474bbd1b89#?tab=log
I also added support access, if anyone wants to take a look at it.

**Comment by mjones-droid** [comment]
Hey @mbuchetics! Sorry you're having issues. 

I think the key line is here:
`app ID capabilities are not in sync with the project capabilities, synchronizing...`

What that tells me is that Bitrise thinks the capabilities for the App ID being pulled from Apple aren't sufficient to cover the project. 

The simplest step is to triple check that the capabilities in the Apple Developer Portal are actually correct. (I know you already did that, but it's worth checking one more time). 

Beyond that, it's a little difficult to troubleshoot based off the error message we have. Would you mind turning on verbose logging for the iOS Auto Provision step to see if we get anything useful?

**Comment by mbuchetics** [comment]
Hi, thank your for your response. I checked the App ID settings on the developer portal and everything seems fine. The log complains about the `Parent Bundle ID` capability, but that's already enabled and set for my `"XC at tinkado Flipbook Clip"` app ID (which was created by Xcode). You can't event disable that for App Clips, it must be enabled and set. Building using Xcode works fine.

I enabled verbose logging (see https://app.bitrise.io/build/fed09d48c2ffe146#?tab=log) but it didn't provide any additional help.

**Comment by mjones-droid** [comment]
Hey @mbuchetics! Thanks for trying verbose logging. You're right, that didn't provide anything useful. Sorry :( 

There's two things I'd like you to try. 

1.) We have an [older, deprecated version of the iOS Auto Provision Step](https://www.bitrise.io/integrations/steps/ios-auto-provision) that requires your Apple ID credentials. Would you mind swapping out the steps for me and trying again?

If the build turns green using the older step then that tells me the problem has to do with something the newer step is doing. It helps focus my troubleshooting efforts. 

2.) Please try building locally from a clean clone and with the Bitrise CLI. More info about this can be found [here](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/) and [here](https://discuss.bitrise.io/t/how-to-debug-your-build-locally-it-works-on-my-mac-pc-but-not-on-bitrise-io/392).

I recognize that the build completes successfully via Xcode on your local machine. There's a lot of variables that change when you run the same build on our machine. This will help us isolate them.

**Comment by mbuchetics** [comment]
Hey @mjones-droid,
I tried 1) and it did work! See build log at https://app.bitrise.io/build/1c3f6f10754c667b#?tab=log
I don't have time to setup 2) right now, is this sufficient information for you now or do you need the local build information as well?

**Comment by mjones-droid** [comment]
Hey @mbuchetics!

Don't worry about my second troubleshooting step. I'm pretty sure we have a bug in the step. I'm going to file a report with the devs. 

For now leave the deprecated step in place.

**Comment by mbuchetics** [comment]
Thank you!

**Comment by mbuchetics** [comment]
Any news here? Would really like to switch to the new step to avoid 2FA prompts.

**Comment by mjones-droid** [comment]
No updates at this time. Sorry. :( I know a bug report has been filed.

**Comment by maxmamis** [comment]
Hi, would also like to bump this issue. Any updates?

**Comment by mjones-droid** [comment]
It looks like this should be fixed. Be aware that in some instances the iOS Autoprovision step fails due to unsupported entitlements which is a different issue. 

If you're still struggling with this, please put in a ticket so we can take a closer look.

**Comment by maxmamis** [comment]
Thanks, I ran into this exact issue earlier today so I've submitted a ticket.
