### ISSUE TITLE
Apple Development are supported ? or only IOS_DEVELOPMENT ?

### ISSUE THREAD

**Issue by daida** [bitrise-steplib/steps-ios-auto-provision-appstoreconnect#26]
Here the result I got with the steps-ios-auto-provision-appstoreconnect

Downloading certificates
2 certificates downloaded:
- Apple Development: xxxx
- Apple Distribution: xxxx
no valid IOS_DEVELOPMENT type certificates uploaded with Team ID (xxxx)

the old step works fine (with the old appStore authentification system) works fine.

Do you support Apple Development certificate ? or I have to switch to IOS_DEVELOPMENT ?

Thanks for your help

**Comment by bitce** [comment]
Hi @daida! I see you closed this but the information might be useful for others - this completely depends on Xcode version. Apple Development has to be used from Xcode 11 and forward, and earlier versions of Xcode would require IOS_DEVELOPMENT type certificates.

**Comment by daida** [comment]
Yes! The error message confuse me! The real error was i did'nt perform an archive on xcode so there are no provioning profiles available..

Maybe you could change te error message to mention ios developper provisioning profiles or apple developer provisioning profiles.

Thanks for yout answer!

**Comment by damiencal** [comment]
Hi @daida and @bitce I came across the same issue you reported above but with the addition of:

![DeepinScreenshot_select-area_20210131130232](https://user-images.githubusercontent.com/2505223/106383175-a9e48e00-63c4-11eb-9502-5b19625b99fa.png)


Ive used the Bitrise key upload tool from the mac that signs and distributes the app with xcode.
So the uploaded keys and profiles should be the right ones in the CodeSign project setting.

I've also tried recreating the Apple Connect Key that is connected to my App Admin account.


Here is a screenshot of my steps:

![DeepinScreenshot_select-area_20210131125915](https://user-images.githubusercontent.com/2505223/106383097-288cfb80-63c4-11eb-80ec-29941d44b64c.png)

**Comment by Roland-Bak** [comment]
Hello there @damiencal 👋

The certificate on the screenshot you sent is one for Bitrise, included in every Auto Provision step by default as is needed for the whole process to work. 

If you still experience this issue, could you please send us a build URL of the related build and enable Support Access on the Settings tab of the app (https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/), so that we may take a closer look?

**Comment by damiencal** [comment]
@Roland-Bak Hi Roland, I ended up contacting Bitrise support. However they replied that Capacitor apps are not yet supported for iOS builds using auto provision.
Till today i have only been using it successfully for Android.

It would be great to support Capacitor, as the process steps should be close to Cordova and Ionic projects.

If you know of any user that figured a workaround please let me know the steps I have to configure to Provision, Archive ios apps and upload builds to Apple Connect.

Thanks
