### ISSUE TITLE
Fail to match iCloud container when re-using existing provisioning profile 

### ISSUE THREAD

**Issue by tomaszkoperski** [bitrise-steplib/steps-ios-auto-provision-appstoreconnect#32]
I'm getting this error:

`failed to check if profile is valid: project uses containers that are missing from the provisioning profile: [iCloud.$(CFBundleIdentifier)]`

whenever I try to run auto provisioning using this plugin.
The problem doesn't happen when I delete the provisioning profiles in App Store Connect (so they are created instead of being pulled down from the ASC API).

Happened here:
https://app.bitrise.io/build/183b9120fcdeaf4a

**Comment by bitce** [comment]
Hi @tomaszkoperski !

Thank you, we're looking into this!

**Comment by daida** [comment]
Hello, I got EXCACTLY the same issue !

**Comment by daida** [comment]
I fix this issues by removing provisoning profiles on Xcode, after Xcode regenerate them and everything works for one build, but the next build will fail

**Comment by bitce** [comment]
The investigation and fixing of this is already in progress, will make sure to post an update here once we can!

**Comment by bitce** [comment]
Hi @tomaszkoperski  and @daida, we just released a new version (0.1.6) of the step that contains the fix. https://github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/releases/tag/0.1.6 
Hope this helps!

**Comment by daida** [comment]
Cool ! thanks !

**Comment by daida** [comment]
Works perfectly !! Thank you very much !
