### ISSUE TITLE
ios-auto-provision-appstoreconnect breaks agvtool

### ISSUE THREAD

**Issue by axelguilmin** [bitrise-steplib/steps-ios-auto-provision-appstoreconnect#39]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? _1.0.0_
- Is the issue reproducible with the latest version? _YES_
- Does the issue happen sporadically, or every time? _EVERY TIME_
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? _NO_

### Issue description

Running a script with `$ xcrun agvtool what-version` after the `ios-auto-provision-appstoreconnect` step fails :
> There does not seem to be a CURRENT_PROJECT_VERSION key set for this project.  Add this key to your target's expert build settings.

Apple Generic versioning is enabled in the project, and the same script works fine if we run it before the `ios-auto-provision-appstoreconnect` step.
It looks like the .xcodeproj is edited and the CURRENT_PROJECT_VERSION field removed.

### Bitrise info

- Build URL: https://app.bitrise.io/build/51a25156f56e55dd
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES_
- Log: 

<details>
  <pre>
+------------------------------------------------------------------------------+
| (0) activate-ssh-key                                                         |
+---+---------------------------------------------------------------+----------+
[REDACTED]
                                          ▼
+------------------------------------------------------------------------------+
| (1) git-clone                                                                |
+---+---------------------------------------------------------------+----------+
[REDACTED]
                                          ▼
+------------------------------------------------------------------------------+
| (2) Do anything with Script step                                             |
+------------------------------------------------------------------------------+
| id: script                                                                   |
| version: 1.1.6                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2021-02-06T10:13:43Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
==> Start
==> Switching to working directory: /Users/vagrant/git
+ xcrun -find agvtool
/Applications/Xcode.app/Contents/Developer/usr/bin/agvtool
+ xcrun agvtool what-version
Current version of project Polagram is: [REDACTED]
==> Script finished with exit code: 0
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ✓ | Do anything with Script step                                  | 9.21 sec |
+---+---------------------------------------------------------------+----------+
                                          ▼
+------------------------------------------------------------------------------+
| (3) ios-auto-provision-appstoreconnect@1                                     |
+------------------------------------------------------------------------------+
| id: ios-auto-provision-appstoreconnect                                       |
| version: 1.0.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-02-06T10:13:52Z                                                   |
+------------------------------------------------------------------------------+
[REDACTED]
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ✓ | ios-auto-provision-appstoreconnect@1                          | 37.99 sec|
+---+---------------------------------------------------------------+----------+
                                          ▼
+------------------------------------------------------------------------------+
| (4) Do anything with Script step                                             |
+------------------------------------------------------------------------------+
| id: script                                                                   |
| version: 1.1.6                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2021-02-06T10:14:30Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
==> Start
==> Switching to working directory: /Users/vagrant/git
+ xcrun -find agvtool
/Applications/Xcode.app/Contents/Developer/usr/bin/agvtool
+ xcrun agvtool what-version
There does not seem to be a CURRENT_PROJECT_VERSION key set for this project.  Add this key to your target's expert build settings.
==> Script finished with exit code: 6
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | Do anything with Script step (exit code: 6)                   | 2.70 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-script/issues             |
| Source: https://github.com/bitrise-io/steps-script                           |
+---+---------------------------------------------------------------+----------+
  </pre>
</details>

### Steps to reproduce

- use the ios-auto-provision-appstoreconnect step
- use agvtool in a script step (or fastlane)

**Comment by MohamedDer** [comment]
I have the same issue. Still working on a workaround script that can fix the broken `xcodeproj ` or `plist` key , and hopefully waiting for the fix

**Comment by Roland-Bak** [comment]
Hello everyone!

I wanted to let you know that we are still working on fixing this, but it is a work in progress.
As soon as we have a solution, we'll let you know! 🙂

**Comment by adborbas** [comment]
Hi all,

Thanks for reporting the issue. The latest version, [1.0.3](https://github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/releases/tag/1.0.3), contains updates related to the project parsing which could potentially resolve this issue.

Could you please retry with the new version?

On the other hand you might also want to check out the [Set Xcode Project Build Number](https://www.bitrise.io/integrations/steps/set-xcode-build-number) Step which can be used to update the bundle's version in `Info.plist`. I'm not sure if this fit your needs or how it could be integrated to your workflow, just I wanted to share it with you. 

Thanks,
Adam

**Comment by adborbas** [comment]
Hi, I'll take your reactions above as confirmation for the issue being resolved and will close this ticket. Please feel free to open a new issue incase the problem reoccurs. Thanks again!
