### ISSUE TITLE
Not signing UITest Target

### ISSUE THREAD

**Issue by appcelerate** [bitrise-steplib/steps-ios-auto-provision-appstoreconnect#47]
### Issue description
This steps fails to check for signing UITest / Unit test targets. Its not checking those targets.

Getting this error : 

❌  error: No profiles for 'com.-------UITests.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.------UITests.xctrunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'UITests' from project 'TestProject')

### Bitrise info

- Build URL: https://app.bitrise.io/build/746abf77486473b2#?tab=log

**Comment by Roland-Bak** [comment]
Hello @appcelerate 👋

Could you please confirm that you have your API key set in your App's Team tab? I can see that you have an Apple ID connected, but for security reason API keys are only visible to their owners.

Have you tried using the iOS Auto Provision with Apple ID step to see if that works?
Another thing you can check is to enable Automatic signing by passing -allowProvisioningUpdates to xcodebuild, just as the logs say. 🙂

**Comment by godrei** [comment]
Hi @appcelerate ,
sorry for my late response!

UITest target signing support added in version 1.1.0, see the related [PR](https://github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/pull/51) and [Release](https://github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/releases/tag/1.1.0) for more info.

I'll close this issue, but if you need more info/help just let us know by opening a new one!
