### ISSUE TITLE
Difference between automatic and api_key connections

### ISSUE THREAD

**Issue by QuentinFarizon** [bitrise-steplib/steps-ios-auto-provision-appstoreconnect#66]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 2.0.1
- Is the issue reproducible with the latest version? YES

### Issue description

I think something is missing in the documentation, I don't understand the difference between :
- automatic: Use the Apple Developer connection based on API key.
- api_key: Use the Apple Developer connection based on API key authentication

Both modes seem to use the Api key connection configured in the "Team" tab of my app. Is there a difference ?

I think the documentation should be clearer here. Examples in this repo don't showcase any difference.

Also, could it be possible to to specify an API key in this step, when multiple are registered ? (and not alwasy take the default one)

Thanks !

**Comment by QuentinFarizon** [comment]
Up, still awaiting clarification :)

**Comment by bitce** [comment]
Hi @QuentinFarizon!

Sorry for missing this question earlier. The difference between the settings in question is that the `automatic` option will use the different session-based connection or step inputs as a fallback if available, while `api_key` will only work with that method specifically.

The way you could use different API key connections at the moment is by downloading the different .p8 keys to the build machines directly. I'll make sure to pass along the request to make this simpler, though this is limited by how the website expects you to select one an account to be using at a time.

**Comment by QuentinFarizon** [comment]
@bitce If there is a difference, the documentation should explicit it.

**Comment by QuentinFarizon** [comment]
Well the documentation is still not clear

**Comment by lpusok** [comment]
Closing as Step is deprecated.
Use _manage-ios-code-signing_ instead: https://github.com/bitrise-steplib/bitrise-step-manage-ios-code-signing/blob/60e41ea0227a0c6ce2a8cd0b17f5301452f46f32/step.yml#L65.
