### ISSUE TITLE
Distribution is not set based on Env Var distribution_type

### ISSUE THREAD

**Issue by OlafAndreas** [bitrise-steplib/steps-ios-auto-provision-appstoreconnect#86]
### Troubleshooting

- [X] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 2.2.1
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

I started to see this issue after transitioning to iOS Auto Provision with App Store Connect API today.

I have multiple steps in a chain, this is a subset of the chain which takes care of configuring environment variables before building the project.

The AdHoc step is run before the Build step. DISTRIBUTION_TYPE is used multiple places.
By default the ios-auto-provision-appstoreconnect@2.2 does not catch the distribution_type as an input, and the only way of fixing it is to manually edit the yaml file and insert the missing `- distribution_type: "$DISTRIBUTION_TYPE"`

```
Firebase:
    envs:
    - DISTRIBUTION_TYPE: ad-hoc
    - APP_CONFIGURATION: QA

Build:
    steps:
    - ios-auto-provision-appstoreconnect@2.2:
        inputs:
        - configuration: "$APP_CONFIGURATION"
    - set-xcode-build-number@1:
        inputs:
        - plist_path: "$PROJECT_DIRECTORY/App/Supporting Files/$BITRISE_SCHEME/$APP_CONFIGURATION/$BITRISE_SCHEME-Info.plist"
    - xcode-project-info@2:
        inputs:
        - info_plist_path: "$PROJECT_DIRECTORY/App/Supporting Files/$BITRISE_SCHEME/$APP_CONFIGURATION/$BITRISE_SCHEME-Info.plist"
    - xcode-archive@4.0:
        inputs:
        - export_method: "$DISTRIBUTION_TYPE"
        - cache_level: none
        - configuration: "$APP_CONFIGURATION"
```

I expect that the Distribution field is overriden by the value found in the environment variable of DISTRIBUTION_TYPE, this expectation fails to be fulfilled.

### Bitrise info

- Build URL: https://app.bitrise.io/build/2fbf9f7c-db9f-4b89-89df-941d93558e53#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES
- Log: 

<details>
  <pre>
Agent version:	1.33.0
Hostname:	prd-atl-std-x-xcode-13-211102140013-zXRanVCyd7qBaD3woGBf8m.local
Start time:	2021-11-02T14:02:05Z
$ bitrise "run" [REDACTED]
  ██████╗ ██╗████████╗██████╗ ██╗███████╗███████╗
  ██╔══██╗██║╚══██╔══╝██╔══██╗██║██╔════╝██╔════╝
  ██████╔╝██║   ██║   ██████╔╝██║███████╗█████╗
  ██╔══██╗██║   ██║   ██╔══██╗██║╚════██║██╔══╝
  ██████╔╝██║   ██║   ██║  ██║██║███████║███████╗
  ╚═════╝ ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝╚══════╝
  version: 1.48.0
INFO[14:02:05] bitrise runs in Secret Filtering mode 
INFO[14:02:05] bitrise runs in Secret Envs Filtering mode 
INFO[14:02:05] bitrise runs in CI mode           
INFO[14:02:05] Running workflows: App --> FirebaseApp --> Firebase --> FirebaseDeploy 
Switching to workflow: App
Switching to workflow: FirebaseApp
Switching to workflow: Firebase
Switching to workflow: Base
+------------------------------------------------------------------------------+
| (0) activate-ssh-key@4.0.5                                                   |
+---+---------------------------------------------------------------+----------+
+---+---------------------------------------------------------------+----------+
| ✓ | activate-ssh-key@4.0.5                                        | 6.03 sec |
+---+---------------------------------------------------------------+----------+
| Update available: 4.0.5 -> 4.1.0                                             |
|                                                                              |
| Release notes are available below                                            |
| https://github.com/bitrise-io/steps-activate-ssh-key/releases                |
+---+---------------------------------------------------------------+----------+
                                          ▼
INFO[14:02:12] Step uses latest version -- Updating StepLib ... 
+------------------------------------------------------------------------------+
| (1) git-clone@4                                                              |
+---+---------------------------------------------------------------+----------+
+---+---------------------------------------------------------------+----------+
| ✓ | git-clone@4                                                   | 27.50 sec|
+---+---------------------------------------------------------------+----------+
| Update available: 4 (4.3.0) -> 6.1.2                                         |
|                                                                              |
| Release notes are available below                                            |
| https://github.com/bitrise-steplib/steps-git-clone/releases                  |
+---+---------------------------------------------------------------+----------+
                                          ▼
+------------------------------------------------------------------------------+
| (2) cache-pull@2                                                             |
+---+---------------------------------------------------------------+----------+
+---+---------------------------------------------------------------+----------+
| ✓ | cache-pull@2                                                  | 17.19 sec|
+---+---------------------------------------------------------------+----------+
                                          ▼
+------------------------------------------------------------------------------+
| (3) cocoapods-install@2                                                      |
+---+---------------------------------------------------------------+----------+
+---+---------------------------------------------------------------+----------+
| ✓ | cocoapods-install@2                                           | 2.2 min  |
+---+---------------------------------------------------------------+----------+
                                          ▼
+------------------------------------------------------------------------------+
| (4) carthage@3                                                               |
+---+---------------------------------------------------------------+----------+
+---+---------------------------------------------------------------+----------+
| ✓ | carthage@3                                                    | 18.19 sec|
+---+---------------------------------------------------------------+----------+
                                          ▼
+------------------------------------------------------------------------------+
| (5) unzip@0.0.3                                                              |
+---+---------------------------------------------------------------+----------+
+---+---------------------------------------------------------------+----------+
| ✓ | unzip@0.0.3                                                   | 4.59 sec |
+---+---------------------------------------------------------------+----------+
                                          ▼
+------------------------------------------------------------------------------+
| (6) cache-push@2                                                             |
+---+---------------------------------------------------------------+----------+
+---+---------------------------------------------------------------+----------+
| ✓ | cache-push@2                                                  | 5.88 sec |
+---+---------------------------------------------------------------+----------+
                                          ▼
Switching to workflow: Build
+------------------------------------------------------------------------------+
| (0) ios-auto-provision-appstoreconnect@2.2                                   |
+------------------------------------------------------------------------------+
| id: ios-auto-provision-appstoreconnect                                       |
| version: 2.2.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-11-02T14:05:41Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
- BitriseConnection: automatic
- APIKeyPath: 
- APIIssuer: 
- TeamID: 
- ProjectPath: App.xcworkspace
- Scheme: App
- Configuration: QA
- SignUITestTargets: false
- RegisterTestDevices: false
- Distribution: development
- MinProfileDaysValid: 0
- CertificateURLList: [REDACTED]
- CertificatePassphraseList: *****
- KeychainPath: /Users/[REDACTED]/Library/Keychains/login.keychain
- KeychainPassword: *****
- VerboseLog: false
- BuildAPIToken: [REDACTED]
- BuildURL: https://app.bitrise.io/build/2fbf9f7c-db9f-4b89-89df-941d93558e53
Analyzing project
Using user defined build configuration: QA instead of the scheme's default one: Release.
Make sure you use the same configuration in further steps.
Configuration: QA
Project team ID: [REDACTED]
Platform: iOS
Application and App Extension targets:
- App
Fetching Apple service connection
Bitrise Apple Developer Connection with API key found
Using Apple service connection with API key.
Initializing Developer Portal client
App Store Connect API client created with base URL: https://api.appstoreconnect.apple.com/
Downloading certificates
1 certificates downloaded:
- Apple Distribution: [REDACTED]
Automatic code signing failed: 
No valid IOS_DEVELOPMENT type certificates uploaded with Team ID ([REDACTED]) 
Maybe you forgot to provide a(n) IOS_DEVELOPMENT type certificate.
Upload a IOS_DEVELOPMENT type certificate (.p12) on the Code Signing tab of the Workflow Editor.
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | ios-auto-provision-appstoreconnect@2.2 (exit code: 1)         | 1.4 min  |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...se-steplib/steps-ios-auto-provision-appstoreconnect/issues |
| Source: ...thub.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect |
+---+---------------------------------------------------------------+----------+
  </pre>
</details>

**Comment by cathyharmon** [comment]
The iOS Auto Provision with AppStore Connect API has a required input "Distribution type".  The default value for this step input is "development".   Unless you override the default by specifying another value, it will use "development".  

Looking at the bitrise.yml, this is not overridden so the default value of "development" will be used.

You can set the value for this step input to be an ENV VAR and set the ENV VAR to what method you want to use, but just setting an ENV VAR without specifying it as the value for the step input will not override the default value.
