### ISSUE TITLE
Latin character may broke to find the certificate

### ISSUE THREAD

**Issue by euharrison** [bitrise-steplib/steps-ios-auto-provision-appstoreconnect#9]
Hi, thanks for the update, this step sounds amazing! 🙏 

I updated my project following this post https://blog.bitrise.io/app-store-connect-api-on-bitrise but actually it's not working.
Before the update, the project was building correctly with the old step of Auto Sign. 

I believe the reason of the broken build is because my certificate has a latin character `ç`.
I already had a similar problem with other step a few months ago.

Does anyone has a clue about it?

```
Code Signing Error: No certificate for team '7H7357N436' matching 'Apple Development: Harrison Mendonña (42A6G4WQ47)' found:  Select a different signing certificate for CODE_SIGN_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 13.5'
```

![Screen Shot 2020-06-24 at 18 40 24](https://user-images.githubusercontent.com/557598/85630540-2f8fa680-b64a-11ea-9f46-e870615948b9.png)

![Screen Shot 2020-06-24 at 18 42 25](https://user-images.githubusercontent.com/557598/85630693-7c737d00-b64a-11ea-9db2-437a7d93140d.png)

**Comment by bitce** [comment]
Hi @euharrison! Sorry to hear about the issue! Can you please send us a build URL where this happens, and enable Support User access in the Settings of the app?

**Comment by euharrison** [comment]
Hi @bitce, thanks for reply

Sure, here is the link https://app.bitrise.io/build/0a74506870d99141#?tab=log and support user access is enabled
