### ISSUE TITLE
Suddenly fails to parse provisioning profiles

### ISSUE THREAD

**Issue by KyLeggiero** [bitrise-steplib/steps-ios-auto-provision-appstoreconnect#92]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? **2.2.2**
- Is the issue reproducible with the latest version? **YES**
- Does the issue happen sporadically, or every time? **EVERY TIME**
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? **NOT APPLICABLE** (local `bitrise` command fails to parse project file)

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

The following error is emitted:

```none
Automatic code signing failed: failed to ensure profiles: failed to find profile: parsing time "2022-05-17T16:18:33.000+00:00" as "2006-01-02T15:04:05.000-0700": cannot parse "0" as "-0700"
```

I'm not aware of anything that has changed since the previous success using this workflow, regarding provisioning profiles and related. Building locally with from Xcode successfully finds profiles and builds.

I attempted deleting and re-downloading profiles from Apple, but that does not appear to have affected this issue.

### Bitrise info

- Build URL: https://app.bitrise.io/build/1e153441-fa35-4acc-85c8-38a4744b0bf7#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: **YES**
- Log: 

<details>
  <pre>
Automatic code signing failed: failed to ensure profiles: failed to find profile: parsing time "2022-05-17T16:18:33.000+00:00" as "2006-01-02T15:04:05.000-0700": cannot parse "0" as "-0700"
  </pre>
</details>

### Steps to reproduce

I have not been able to reproduce this with a test project

**Comment by patrickhammond** [comment]
We also started experiencing this in the last few hours. Have attempted deleting the interesting provisioning profiles from Apple's developer site but get a similar error around parsing time when it attempts to recreate those profiles.

With step debug logs turned on it appears to be that the issue is related to GET and POST requests to this endpoint:
 https://api.appstoreconnect.apple.com/v1/profiles

**Comment by ayn** [comment]
Same:

> Automatic code signing failed: failed to ensure profiles: failed to find profile: parsing time "2022-04-29T18:01:51.000+00:00" as "2006-01-02T15:04:05.000-0700": cannot parse "0" as "-0700"

**Comment by geyserz** [comment]
same: 

> Automatic code signing failed: failed to ensure profiles: failed to find profile: parsing time "2022-12-16T19:01:45.000+00:00" as "2006-01-02T15:04:05.000-0700": cannot parse "0" as "-0700"

**Comment by tonyhunt** [comment]
Same:

> failed to find profile: parsing time "2022-07-23T10:34:20.000+00:00" as "2006-01-02T15:04:05.000-0700": cannot parse "0" as "-0700"

**Comment by cbackas** [comment]
I wont paste mine... but same

**Comment by CarsonRedeye** [comment]
Does anyone have a workaround? I assume we have to set up provisioning manually now?

**Comment by ameedsayeh** [comment]
Same issue is happening here as well

**Comment by mleatherb** [comment]
We are also seeing this same error using everything from 1.1.3 > 2.2. We're using API key for auth

**Comment by shams-ahmed** [comment]
@mateherber discovered the underlying problem and is pushing out a fix right now. Version (2.2.3) should be out very soon.

**Comment by shams-ahmed** [comment]
The step has now been released. Please let us know if you are still experiencing the same issue.

**Comment by YontiLevin** [comment]
still getting ```error: exportArchive: Signing certificate is invalid.```
