### ISSUE TITLE
Automatic code signing failed

### ISSUE THREAD

**Issue by QuentinFarizon** [bitrise-steplib/steps-ios-auto-provision-appstoreconnect#96]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 2.2.4
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE

### Issue description

All our builds are failing at step "ios-auto-provision-appstoreconnect", on different projects with different API keys.
We didn't change anything on Bitrise configuration.

```
Fetching Apple Service connection
Bitrise Apple Developer Connection with API key found
Using Apple service connection with API key.
Initializing Developer Portal client
App Store Connect API client created with base URL: https://api.appstoreconnect.apple.com/
Downloading certificates
1 certificates downloaded:
- Serial: 1433(redacted)22132, Name: iPhone Distribution: (redacted), Team: (redacted), Expiry: 2022-08-25 13:45:48 +0000 UTC
Certificate (Serial: 1433(redacted)22132, Name: iPhone Distribution: (redacted), Team: (redacted), Expiry: 2022-08-25 13:45:48 +0000 UTC) not found on Developer Portal: failed to fetch certificate (6bda8(redacted)194): GET https://api.appstoreconnect.apple.com/v1/certificates?filter%5BserialNumber%5D=6bda8e(redacted)1194: 401
- NOT_AUTHORIZED: Authentication credentials are missing or invalid.: Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens
Automatic code signing failed: failed to get valid certificates: not found any of the following IOS_DISTRIBUTION certificates on Developer Portal:
- Serial: 143362(redacted)2132, Name: iPhone Distribution: (redacted), Team: (redacted), Expiry: 2022-08-25 13:45:48 +0000 UTC
```

### Bitrise info

- Build URL: https://app.bitrise.io/build/0c3b0e46-bf09-4c1b-b8ee-9701b2d0dcd1#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES

**Comment by shams-ahmed** [comment]
@QuentinFarizon `401 NOT_AUTHORIZED: Authentication credentials are missing or invalid` might be related to an expired Apple Service connection. see more [here](https://devcenter.bitrise.io/en/accounts/connecting-to-services/connecting-to-an-apple-service-with-api-key.html#adding-api-key-authentication-data-on-bitrise)

**Comment by QuentinFarizon** [comment]
It sounds like it could be related, but it started failing at the same time in two projects with differents Apple Service Connections, created at different times

**Comment by shams-ahmed** [comment]
@QuentinFarizon On another note, can double-check your certificate is available on Apple portal, it may have been deleted or recreated and no longer matches with the one supplied to Bitrise.

**Comment by QuentinFarizon** [comment]
Well, the 2 certificates belong to two different Apple account, managed by two different administrators (and I'm not an administrator so I can't check)

**Comment by QuentinFarizon** [comment]
Issue is now solved. Probably an issue on Apple side ?

**Comment by shams-ahmed** [comment]
@QuentinFarizon likely... but hard to say since their status page is mostly green
