### ISSUE TITLE
Automatic code signing failed

### ISSUE THREAD

**Issue by QuentinFarizon** [bitrise-steplib/steps-ios-auto-provision-appstoreconnect#97]
https://github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/issues/96 was closed, but I still gets the issue randomly, without any configuration change.

Example : https://app.bitrise.io/build/b0ef04af-9dbc-46a2-88ce-94a42d89a831#?tab=log

**Comment by pballada** [comment]
same issue here
